# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0002_inspiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='title',
        ),
    ]
