# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0003_remove_inspiration_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='online_reference',
            field=models.URLField(blank=True, max_length=264),
        ),
    ]
