# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0004_auto_20180709_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='author',
            field=models.CharField(default='Unknown', max_length=264),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='cover_photo',
            field=models.URLField(blank=True, max_length=264),
        ),
    ]
