# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0005_auto_20180709_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=264)),
                ('cover_photo', models.URLField(blank=True, max_length=264)),
                ('online_reference', models.URLField(blank=True, max_length=264)),
                ('description', models.TextField()),
            ],
        ),
    ]
