# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0006_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
