# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0008_auto_20180714_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_photo_local',
            field=models.FilePathField(blank=True, path='/home/brettcrowley77/bcrowley-website/BCrowley_Website/static/img'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_photo_remote',
            field=models.URLField(blank=True, max_length=264),
        ),
    ]
