# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0009_auto_20180714_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='online_reference',
            field=models.URLField(blank=True, max_length=264),
        ),
    ]
