# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCrowley_App', '0010_project_online_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_photo_local',
            field=models.FilePathField(blank=True, path='/img'),
        ),
    ]
